name: Update IPTV List
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4 # 升级解决 Node.js 20 弃用警告
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Filter
        run: python filter.py

      - name: Commit and Push
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "action@github.com"
          # 使用你喜欢的模糊匹配
          git add *.txt *.m3u
          if ! git diff --staged --quiet; then
            git commit -m "Update IPTV lists: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected."
          fi
